# Generated by Django 5.2.6 on 2026-03-15 17:50

import Faturamento.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impostos',
            fields=[
                ('id_impostos', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'impostos',
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id_modalidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'modalidade',
            },
        ),
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=50)),
                ('simbolo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'moedas',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'pagamento',
            },
        ),
        migrations.CreateModel(
            name='Precos',
            fields=[
                ('id_precos', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'precos',
            },
        ),
        migrations.CreateModel(
            name='TaxReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Motivo de IVA',
                'verbose_name_plural': 'Motivos de IVA',
                'db_table': 'tax_reasons',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vendedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'vendedor',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('zona', models.CharField(max_length=40)),
                ('moeda', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('morada', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Portugal', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nif', models.CharField(max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='DocumentoFinalizado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura Recibo'), ('FS', 'Fatura Simplificada'), ('NC', 'Nota de Crédito'), ('GT', 'Guia de Transporte')], max_length=2)),
                ('serie', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('cliente_id', models.BigIntegerField()),
                ('cliente_nome', models.CharField(max_length=255)),
                ('cliente_morada1', models.CharField(max_length=128)),
                ('cliente_morada2', models.CharField(blank=True, max_length=128, null=True)),
                ('cliente_codigo_postal', models.CharField(max_length=12)),
                ('cliente_concelho', models.CharField(max_length=40)),
                ('cliente_pais', models.CharField(max_length=40)),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cliente_contribuinte', models.CharField(max_length=20)),
                ('empresa_nome', models.CharField(max_length=150)),
                ('empresa_morada', models.CharField(max_length=255)),
                ('empresa_codigo_postal', models.CharField(max_length=20)),
                ('empresa_cidade', models.CharField(max_length=100)),
                ('empresa_pais', models.CharField(max_length=100)),
                ('empresa_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('empresa_contribuinte', models.CharField(max_length=20)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('modalidade_nome', models.CharField(blank=True, max_length=40, null=True)),
                ('moeda_simbolo', models.CharField(max_length=50)),
                ('ordem_compra', models.CharField(blank=True, max_length=128, null=True)),
                ('numero_compromisso', models.CharField(blank=True, max_length=128, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('rodape', models.TextField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('local_carga', models.CharField(blank=True, max_length=255, null=True)),
                ('local_descarga', models.CharField(blank=True, max_length=255, null=True)),
                ('data_carga', models.DateTimeField(blank=True, null=True)),
                ('data_descarga', models.DateTimeField(blank=True, null=True)),
                ('expedicao', models.CharField(blank=True, max_length=255, null=True)),
                ('transporte_descricao', models.CharField(blank=True, max_length=40, null=True)),
                ('estado', models.CharField(choices=[('Finalizado', 'Finalizado'), ('Anulado', 'Anulado')], default='Finalizado', max_length=20)),
                ('estado_pagamento', models.CharField(choices=[('Pendente', 'Pendente'), ('Parcial', 'Parcial'), ('Pago', 'Pago')], default='Pendente', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('codigo_at_tributaria', models.CharField(blank=True, help_text='Código fornecido pela Autoridade Tributária', max_length=20, null=True, verbose_name='Código AT')),
                ('documento_origem', models.ForeignKey(blank=True, db_column='documento_origem_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_retificativos', to='Faturamento.documentofinalizado')),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_finalizados', to='Faturamento.empresa')),
            ],
            options={
                'db_table': 'documento_finalizado',
                'ordering': ['-criado_em'],
                'unique_together': {('tipo', 'serie', 'numero', 'ano', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='Cliente1',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('morada1', models.CharField(max_length=128)),
                ('morada2', models.CharField(blank=True, max_length=128, null=True)),
                ('codigo_postal', models.CharField(max_length=12)),
                ('telemovel', models.CharField(blank=True, max_length=20, null=True)),
                ('sigla', models.CharField(max_length=3)),
                ('contribuinte', models.CharField(max_length=20, validators=[Faturamento.models.nif_validator])),
                ('pais', models.CharField(max_length=40)),
                ('distrito', models.CharField(max_length=40)),
                ('concelho', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='Faturamento.empresa')),
                ('impostos', models.ForeignKey(db_column='impostos', on_delete=django.db.models.deletion.PROTECT, to='Faturamento.impostos')),
                ('modalidade', models.ForeignKey(blank=True, db_column='modalidade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.modalidade')),
                ('pagamento', models.ForeignKey(blank=True, db_column='pagamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.pagamento')),
                ('precos', models.ForeignKey(blank=True, db_column='precos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.precos')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id_artigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(default='Produto', max_length=20)),
                ('empresa', models.ForeignKey(db_column='empresa_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='Faturamento.empresa')),
            ],
            options={
                'db_table': 'artigo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentoTemp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura Recibo'), ('FS', 'Fatura Simplificada'), ('NC', 'Nota de Crédito')], max_length=2)),
                ('serie', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('data_emissao', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Em Revisão', 'Em Revisão')], default='Rascunho', max_length=20)),
                ('transporte', models.CharField(blank=True, max_length=255, null=True)),
                ('ordem_compra', models.CharField(blank=True, max_length=128, null=True)),
                ('numero_compromisso', models.CharField(blank=True, max_length=128, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('rodape', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('local_carga', models.CharField(blank=True, max_length=255, null=True)),
                ('local_descarga', models.CharField(blank=True, max_length=255, null=True)),
                ('data_carga', models.DateTimeField(blank=True, null=True)),
                ('data_descarga', models.DateTimeField(blank=True, null=True)),
                ('expedicao', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.cliente1')),
                ('documento_origem', models.ForeignKey(blank=True, db_column='documento_origem_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_temp_associados', to='Faturamento.documentofinalizado')),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contadores_temporarios', to='Faturamento.empresa')),
                ('impostos', models.ForeignKey(db_column='impostos_id', on_delete=django.db.models.deletion.PROTECT, to='Faturamento.impostos')),
                ('moeda', models.ForeignKey(db_column='moeda_id', default=15, on_delete=django.db.models.deletion.PROTECT, to='Faturamento.moeda')),
                ('pagamento', models.ForeignKey(blank=True, db_column='pagamento_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='Faturamento.pagamento')),
            ],
            options={
                'db_table': 'documento_temp',
                'ordering': ['-criado_em'],
                'unique_together': {('tipo', 'serie', 'numero', 'ano', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('RE', 'Recibo')], default='RE', max_length=2)),
                ('serie', models.CharField(default='NC', max_length=10)),
                ('numero', models.IntegerField(default=5000)),
                ('ano', models.IntegerField(default=2026)),
                ('cliente_id', models.BigIntegerField(default=1)),
                ('data_emissao', models.DateField(default=django.utils.timezone.now)),
                ('modalidade_nome', models.CharField(blank=True, help_text='Ex: Transferência, Numerário', max_length=40, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('Normal', 'Normal'), ('Anulado', 'Anulado')], default='Normal', max_length=10)),
                ('data_anulacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='Faturamento.empresa')),
            ],
            options={
                'db_table': 'recibo',
                'ordering': ['-criado_em'],
                'unique_together': {('tipo', 'serie', 'numero', 'ano', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='ReciboLinhas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('documento_tipo', models.CharField(max_length=20)),
                ('documento_numero', models.CharField(max_length=50)),
                ('data_emissao', models.DateField()),
                ('valor_documento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_em_divida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_linhas', to='Faturamento.empresa')),
                ('id_doc_final', models.ForeignKey(db_column='id_doc_final', on_delete=django.db.models.deletion.PROTECT, to='Faturamento.documentofinalizado')),
                ('id_recibo_final', models.ForeignKey(db_column='id_recibo', on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='Faturamento.recibo')),
            ],
            options={
                'db_table': 'recibo_linhas',
            },
        ),
        migrations.CreateModel(
            name='FinArtigos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fin_artigos', to='Faturamento.empresa')),
                ('id_art', models.ForeignKey(db_column='id_art', on_delete=django.db.models.deletion.PROTECT, to='Faturamento.artigo')),
                ('id_final', models.ForeignKey(db_column='id_temp', on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='Faturamento.documentofinalizado')),
                ('motivo', models.ForeignKey(blank=True, db_column='motivo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.taxreason')),
            ],
            options={
                'db_table': 'final_artigos',
            },
        ),
        migrations.CreateModel(
            name='TempArtigos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contadores_artigos_temporarios', to='Faturamento.empresa')),
                ('id_art', models.ForeignKey(db_column='id_art', on_delete=django.db.models.deletion.PROTECT, to='Faturamento.artigo')),
                ('id_temp', models.ForeignKey(db_column='id_temp', on_delete=django.db.models.deletion.CASCADE, to='Faturamento.documentotemp')),
                ('motivo', models.ForeignKey(blank=True, db_column='motivo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.taxreason')),
            ],
            options={
                'db_table': 'temp_artigos',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=40)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transportes', to='Faturamento.empresa')),
            ],
            options={
                'db_table': 'transporte',
            },
        ),
        migrations.AddField(
            model_name='cliente1',
            name='transporte',
            field=models.ForeignKey(blank=True, db_column='transporte', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.transporte'),
        ),
        migrations.AddField(
            model_name='cliente1',
            name='vendedor',
            field=models.ForeignKey(db_column='vendedor', on_delete=django.db.models.deletion.PROTECT, to='Faturamento.vendedor'),
        ),
        migrations.AddField(
            model_name='cliente1',
            name='zona',
            field=models.ForeignKey(blank=True, db_column='zona', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.zona'),
        ),
        migrations.CreateModel(
            name='DocumentoFinalizadoContador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura-Recibo'), ('FS', 'Fatura Simplificada'), ('NC', 'Nota de Crédito'), ('GT', 'Guia de Transporte')], max_length=2)),
                ('serie', models.CharField(default='A', max_length=10)),
                ('ano', models.IntegerField()),
                ('ultimo_numero', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contadores_finais_documentos', to='Faturamento.empresa')),
            ],
            options={
                'db_table': 'documento_contador_final',
                'unique_together': {('tipo', 'serie', 'ano', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoContador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura-Recibo'), ('FS', 'Fatura Simplificada'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito'), ('GT', 'Guia de Transporte')], max_length=2)),
                ('serie', models.CharField(default='A', max_length=10)),
                ('ano', models.IntegerField()),
                ('ultimo_numero', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contadores', to='Faturamento.empresa')),
            ],
            options={
                'db_table': 'documento_contador',
                'unique_together': {('tipo', 'serie', 'ano', 'empresa')},
            },
        ),
    ]
