# Generated by Django 5.2.6 on 2025-10-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=20)),
                ('morada', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('localidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('telemovel', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('condicoes_pagamento', models.CharField(blank=True, max_length=50)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('moeda', models.CharField(default='EUR', max_length=10)),
                ('tipo_cliente', models.CharField(blank=True, max_length=50)),
                ('regime_iva', models.CharField(blank=True, max_length=50)),
                ('conta_corrente', models.CharField(blank=True, max_length=50)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
