# Generated by Django 5.2.6 on 2025-10-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faturamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='condicoes_pagamento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='conta_corrente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='limite_credito',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='moeda',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='regime_iva',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='saldo_inicial',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telemovel',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='website',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
