# Generated by Django 5.2.6 on 2026-03-12 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faturamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente1',
            name='modalidade',
            field=models.ForeignKey(blank=True, db_column='modalidade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.modalidade'),
        ),
        migrations.AlterField(
            model_name='cliente1',
            name='pagamento',
            field=models.ForeignKey(blank=True, db_column='pagamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.pagamento'),
        ),
        migrations.AlterField(
            model_name='cliente1',
            name='precos',
            field=models.ForeignKey(blank=True, db_column='precos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.precos'),
        ),
        migrations.AlterField(
            model_name='cliente1',
            name='transporte',
            field=models.ForeignKey(blank=True, db_column='transporte', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.transporte'),
        ),
        migrations.AlterField(
            model_name='cliente1',
            name='zona',
            field=models.ForeignKey(blank=True, db_column='zona', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.zona'),
        ),
    ]
