# Generated by Django 5.2.6 on 2026-01-16 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faturamento', '0003_cliente_user_alter_cliente_morada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id_artigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'artigo',
            },
        ),
        migrations.CreateModel(
            name='Cliente1',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('morada1', models.CharField(max_length=128)),
                ('morada2', models.CharField(blank=True, max_length=128, null=True)),
                ('codigo_postal', models.CharField(max_length=12)),
                ('telemovel', models.CharField(blank=True, max_length=20, null=True)),
                ('sigla', models.CharField(max_length=3)),
                ('contribuinte', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=40)),
                ('distrito', models.CharField(max_length=40)),
                ('concelho', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura-Recibo'), ('FS', 'Fatura Simplificada'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito')], max_length=2)),
                ('serie', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('data_emissao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faturamento.cliente1')),
            ],
            options={
                'unique_together': {('tipo', 'serie', 'numero', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Impostos',
            fields=[
                ('id_impostos', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'impostos',
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id_modalidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'modalidade',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'pagamento',
            },
        ),
        migrations.CreateModel(
            name='Precos',
            fields=[
                ('id_precos', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'precos',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'transporte',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vendedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'vendedor',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('zona', models.CharField(max_length=40)),
                ('moeda', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Faturamento.documento')),
                ('estado', models.CharField(choices=[('Pendente', 'Pendente'), ('Parcial', 'Parcial'), ('Pago', 'Pago')], default='Pendente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FaturaRecibo',
            fields=[
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Faturamento.documento')),
                ('meio_pagamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Faturamento.documento')),
                ('motivo', models.CharField(max_length=255)),
                ('documento_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='Faturamento.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Faturamento.documento')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fatura_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Faturamento.fatura')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoContador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura-Recibo'), ('FS', 'Fatura Simplificada'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito')], max_length=2)),
                ('serie', models.CharField(max_length=10)),
                ('ano', models.IntegerField()),
                ('ultimo_numero', models.IntegerField()),
            ],
            options={
                'unique_together': {('tipo', 'serie', 'ano')},
            },
        ),
        migrations.AddField(
            model_name='cliente1',
            name='impostos',
            field=models.ForeignKey(db_column='impostos', on_delete=django.db.models.deletion.PROTECT, to='Faturamento.impostos'),
        ),
        migrations.AddField(
            model_name='cliente1',
            name='modalidade',
            field=models.ForeignKey(db_column='modalidade', on_delete=django.db.models.deletion.PROTECT, to='Faturamento.modalidade'),
        ),
        migrations.AddField(
            model_name='cliente1',
            name='pagamento',
            field=models.ForeignKey(db_column='pagamento', on_delete=django.db.models.deletion.PROTECT, to='Faturamento.pagamento'),
        ),
        migrations.AddField(
            model_name='cliente1',
            name='precos',
            field=models.ForeignKey(db_column='precos', on_delete=django.db.models.deletion.PROTECT, to='Faturamento.precos'),
        ),
        migrations.AddField(
            model_name='cliente1',
            name='transporte',
            field=models.ForeignKey(db_column='transporte', on_delete=django.db.models.deletion.PROTECT, to='Faturamento.transporte'),
        ),
        migrations.AddField(
            model_name='cliente1',
            name='vendedor',
            field=models.ForeignKey(db_column='vendedor', on_delete=django.db.models.deletion.PROTECT, to='Faturamento.vendedor'),
        ),
        migrations.AddField(
            model_name='cliente1',
            name='zona',
            field=models.ForeignKey(db_column='zona', on_delete=django.db.models.deletion.PROTECT, to='Faturamento.zona'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
