# Generated by Django 5.2.6 on 2026-01-22 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faturamento', '0004_artigo_cliente1_documento_impostos_modalidade_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='artigo',
            name='tipo',
            field=models.CharField(default='Produto', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='pago',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Parcial', 'Parcial'), ('Pago', 'Pago')], default='Pendente', max_length=10),
        ),
        migrations.AddField(
            model_name='documento',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, to='Faturamento.cliente1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='Faturamento.documento'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='Faturamento.documento'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fatura_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='Faturamento.fatura'),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('tipo', 'numero', 'cliente', 'data_emissao')},
        ),
        migrations.AlterModelTable(
            name='documento',
            table='documento',
        ),
        migrations.AlterModelTable(
            name='documentocontador',
            table='documento_contador',
        ),
        migrations.AlterModelTable(
            name='fatura',
            table='fatura',
        ),
        migrations.AlterModelTable(
            name='faturarecibo',
            table='fatura_recibo',
        ),
        migrations.AlterModelTable(
            name='notacredito',
            table='nota_credito',
        ),
        migrations.AlterModelTable(
            name='recibo',
            table='recibo',
        ),
    ]
